### PR TITLE
Added attachment support to sendHtmlEmail method

### PR DESCRIPTION
**Pull request by cristianooliveira**

### CODE REVIEW

**Comment by cristianooliveira** [comment]
Just made the changes, thanks!

**Comment by seeruk** [comment]
Cool, thanks @CristianoOliveira. Sorry for the delay in getting this merged, just had to verify it was fine to merge it.

**Comment by cristianooliveira** [comment]
No problem, of course you need to verify it. Thanks

**Comment by nunojsferreira** [comment]
@SeerUK can you also merge to master? So we can update with composer.

**Pull request merged**
